// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqI6Dnau2uIA2oJXw1TViZQaINlcuxDEA',
    appId: '1:282405254061:web:597bc073721ddf27f8a724',
    messagingSenderId: '282405254061',
    projectId: 'cpadteam03',
    authDomain: 'cpadteam03.firebaseapp.com',
    storageBucket: 'cpadteam03.firebasestorage.app',
    measurementId: 'G-X0Q67G5V88',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAo1nTdQhLhnTIIMQZg32sKgyrlzqVCtUE',
    appId: '1:282405254061:android:329f3c9a431ed585f8a724',
    messagingSenderId: '282405254061',
    projectId: 'cpadteam03',
    storageBucket: 'cpadteam03.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6_8hLqh_BJkOruxiApuz03ZDf3-qiaIE',
    appId: '1:282405254061:ios:3d8f37de1e7a09e3f8a724',
    messagingSenderId: '282405254061',
    projectId: 'cpadteam03',
    storageBucket: 'cpadteam03.firebasestorage.app',
    iosBundleId: 'com.example.devEmotionTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6_8hLqh_BJkOruxiApuz03ZDf3-qiaIE',
    appId: '1:282405254061:ios:3d8f37de1e7a09e3f8a724',
    messagingSenderId: '282405254061',
    projectId: 'cpadteam03',
    storageBucket: 'cpadteam03.firebasestorage.app',
    iosBundleId: 'com.example.devEmotionTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqI6Dnau2uIA2oJXw1TViZQaINlcuxDEA',
    appId: '1:282405254061:web:959ecb7db4d161cdf8a724',
    messagingSenderId: '282405254061',
    projectId: 'cpadteam03',
    authDomain: 'cpadteam03.firebaseapp.com',
    storageBucket: 'cpadteam03.firebasestorage.app',
    measurementId: 'G-BDWNP821XS',
  );
}
