name: mood_habit_tracker
description: A Flutter app for mood and habit tracking with TFLite image input.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5 # For state management
  image_picker: ^1.1.2 # For picking images from camera or gallery
  image: ^4.0.17
  intl: ^0.19.0 # For date formatting
  firebase_core: ^3.1.0
  cloud_firestore: ^5.0.1
  camera: ^0.11.0+1 # For camera access
  tflite_flutter: ^0.11.0
  change_app_package_name: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/model.tflite # Make sure this matches your model file name and path
    - assets/labels.txt # Path to your labels file
